# DC
STRUCT_WEIGHT = 1
CONTENT_WEIGHT = 1

COST_STRUCT_EASY_EASY = 0.1 * STRUCT_WEIGHT
COST_STRUCT_EASY = 1 * STRUCT_WEIGHT
COST_STRUCT_MID_EASY = 2 * STRUCT_WEIGHT
COST_STRUCT_MID = 2 * STRUCT_WEIGHT
COST_STRUCT_HARD = 3 * STRUCT_WEIGHT

COST_CONTENT_EASY_EASY = 0.2 * CONTENT_WEIGHT
COST_CONTENT_EASY = 1 * CONTENT_WEIGHT
COST_CONTENT_MID_EASY = 0.2 * CONTENT_WEIGHT
COST_CONTENT_MID = 2 * CONTENT_WEIGHT
COST_CONTENT_HARD = 3 * CONTENT_WEIGHT

FEATURES_COST_PAGEGRAPH_DC = {
    "FEATURE_IN_DEGREE" : COST_STRUCT_EASY_EASY,
    "FEATURE_OUT_DEGREE" : COST_STRUCT_EASY_EASY,
    "FEATURE_IN_OUT_DEGREE" : COST_STRUCT_EASY_EASY,
    "FEATURE_URL_LENGTH" : COST_CONTENT_EASY_EASY,
    "FEATURE_SEMICOLON_IN_QUERY_0" : COST_CONTENT_EASY / 2,
    "FEATURE_SEMICOLON_IN_QUERY_1" : COST_CONTENT_EASY / 2,
    "FEATURE_PARENT_IN_DEGREE" : COST_STRUCT_MID,
    "FEATURE_PARENT_OUT_DEGREE" : COST_STRUCT_MID,
    "FEATURE_PARENT_IN_OUT_DEGREE" : COST_STRUCT_MID,
    "FEATURE_AVERAGE_DEGREE_CONNECTIVITY" : COST_STRUCT_HARD,
    "FEATURE_MODIFIED_BY_SCRIPT_0" : COST_CONTENT_MID / 2,
    "FEATURE_MODIFIED_BY_SCRIPT_1" : COST_CONTENT_MID / 2,
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT_0" : COST_CONTENT_MID / 2,
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT_1" : COST_CONTENT_MID / 2,
}


# HSC
STRUCT_WEIGHT = 10
CONTENT_WEIGHT = 1

COST_STRUCT_EASY_EASY = 0.1 * STRUCT_WEIGHT
COST_STRUCT_EASY = 1 * STRUCT_WEIGHT
COST_STRUCT_MID_EASY = 2 * STRUCT_WEIGHT
COST_STRUCT_MID = 2 * STRUCT_WEIGHT
COST_STRUCT_HARD = 3 * STRUCT_WEIGHT

COST_CONTENT_EASY_EASY = 0.2 * CONTENT_WEIGHT
COST_CONTENT_EASY = 1 * CONTENT_WEIGHT
COST_CONTENT_MID_EASY = 0.2 * CONTENT_WEIGHT
COST_CONTENT_MID = 2 * CONTENT_WEIGHT
COST_CONTENT_HARD = 3 * CONTENT_WEIGHT

FEATURES_COST_PAGEGRAPH_HSC = {
    "FEATURE_IN_DEGREE" : COST_STRUCT_EASY_EASY,
    "FEATURE_OUT_DEGREE" : COST_STRUCT_EASY_EASY,
    "FEATURE_IN_OUT_DEGREE" : COST_STRUCT_EASY_EASY,
    "FEATURE_URL_LENGTH" : COST_CONTENT_EASY_EASY,
    "FEATURE_SEMICOLON_IN_QUERY_0" : COST_CONTENT_EASY / 2,
    "FEATURE_SEMICOLON_IN_QUERY_1" : COST_CONTENT_EASY / 2,
    "FEATURE_PARENT_IN_DEGREE" : COST_STRUCT_MID,
    "FEATURE_PARENT_OUT_DEGREE" : COST_STRUCT_MID,
    "FEATURE_PARENT_IN_OUT_DEGREE" : COST_STRUCT_MID,
    "FEATURE_AVERAGE_DEGREE_CONNECTIVITY" : COST_STRUCT_HARD,
    "FEATURE_MODIFIED_BY_SCRIPT_0" : COST_CONTENT_MID / 2,
    "FEATURE_MODIFIED_BY_SCRIPT_1" : COST_CONTENT_MID / 2,
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT_0" : COST_CONTENT_MID / 2,
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT_1" : COST_CONTENT_MID / 2,
}


# HCC
STRUCT_WEIGHT = 1
CONTENT_WEIGHT = 10

COST_STRUCT_EASY_EASY = 0.1 * STRUCT_WEIGHT
COST_STRUCT_EASY = 1 * STRUCT_WEIGHT
COST_STRUCT_MID_EASY = 2 * STRUCT_WEIGHT
COST_STRUCT_MID = 2 * STRUCT_WEIGHT
COST_STRUCT_HARD = 3 * STRUCT_WEIGHT

COST_CONTENT_EASY_EASY = 0.2 * CONTENT_WEIGHT
COST_CONTENT_EASY = 1 * CONTENT_WEIGHT
COST_CONTENT_MID_EASY = 0.2 * CONTENT_WEIGHT
COST_CONTENT_MID = 2 * CONTENT_WEIGHT
COST_CONTENT_HARD = 3 * CONTENT_WEIGHT

FEATURES_COST_PAGEGRAPH_HCC = {
    "FEATURE_IN_DEGREE" : COST_STRUCT_EASY_EASY,
    "FEATURE_OUT_DEGREE" : COST_STRUCT_EASY_EASY,
    "FEATURE_IN_OUT_DEGREE" : COST_STRUCT_EASY_EASY,
    "FEATURE_URL_LENGTH" : COST_CONTENT_EASY_EASY,
    "FEATURE_SEMICOLON_IN_QUERY_0" : COST_CONTENT_EASY / 2,
    "FEATURE_SEMICOLON_IN_QUERY_1" : COST_CONTENT_EASY / 2,
    "FEATURE_PARENT_IN_DEGREE" : COST_STRUCT_MID,
    "FEATURE_PARENT_OUT_DEGREE" : COST_STRUCT_MID,
    "FEATURE_PARENT_IN_OUT_DEGREE" : COST_STRUCT_MID,
    "FEATURE_AVERAGE_DEGREE_CONNECTIVITY" : COST_STRUCT_HARD,
    "FEATURE_MODIFIED_BY_SCRIPT_0" : COST_CONTENT_MID / 2,
    "FEATURE_MODIFIED_BY_SCRIPT_1" : COST_CONTENT_MID / 2,
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT_0" : COST_CONTENT_MID / 2,
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT_1" : COST_CONTENT_MID / 2,
}