FEATURES_TO_PERTURBE = [
    "FEATURE_GRAPH_NODES",
    "FEATURE_GRAPH_EDGES",
    "FEATURE_URL_LENGTH",
    "FEATURE_AD_KEYWORD",
    "FEATURE_SPECIAL_CHAR_AD_KEYWORD",
    "FEATURE_SEMICOLON_PRESENT",
    "FEATURE_BASE_DOMAIN_IN_QS",
    "FEATURE_AD_DIMENSIONS_IN_QS",
    "FEATURE_INBOUND_OUTBOUND_CONNECTIONS",
    "FEATURE_ASCENDANTS_AD_KEYWORD",
    "FEATURE_SCREEN_DIMENSIONS_IN_QS",
    "FEATURE_AD_DIMENSIONS_IN_COMPLETE_URL",
    "FEATURE_FIRST_NUMBER_OF_SIBLINGS",
    "FEATURE_FIRST_PARENT_NUMBER_OF_SIBLINGS",
    "FEATURE_FIRST_PARENT_SIBLING_AD_ATTRIBUTE",
    "FEATURE_FIRST_PARENT_INBOUND_CONNECTIONS",
    "FEATURE_FIRST_PARENT_OUTBOUND_CONNECTIONS",
    "FEATURE_FIRST_PARENT_INBOUND_OUTBOUND_CONNECTIONS",
    "FEATURE_AVERAGE_DEGREE_CONNECTIVITY",
    "FEATURE_FIRST_PARENT_TAG_NAME",
    #
    "FEATURE_VALID_QS",
    "FEATURE_FIRST_PARENT_ASYNC",
    "FEATURE_FIRST_PARENT_DEFER",
    "FEATURE_FIRST_PARENT_ATTR_ADDED_BY_SCRIPT",
    "FEATURE_FIRST_PARENT_ATTR_MODIFIED_BY_SCRIPT",
    "FEATURE_OUTBOUND_CONNECTIONS",
]

FEATURES_TO_PERTURBE_NUMERIC = [
    "FEATURE_GRAPH_NODES",
    "FEATURE_GRAPH_EDGES",
    "FEATURE_URL_LENGTH",
    "FEATURE_INBOUND_OUTBOUND_CONNECTIONS",
    "FEATURE_FIRST_NUMBER_OF_SIBLINGS",
    "FEATURE_FIRST_PARENT_NUMBER_OF_SIBLINGS",
    "FEATURE_FIRST_PARENT_INBOUND_CONNECTIONS",
    "FEATURE_FIRST_PARENT_OUTBOUND_CONNECTIONS",
    "FEATURE_FIRST_PARENT_INBOUND_OUTBOUND_CONNECTIONS",
    "FEATURE_AVERAGE_DEGREE_CONNECTIVITY",
    "FEATURE_OUTBOUND_CONNECTIONS",
]

FEATURES_TO_PERTURBE_BINARY = [
    "FEATURE_AD_KEYWORD",
    "FEATURE_SPECIAL_CHAR_AD_KEYWORD",
    "FEATURE_SEMICOLON_PRESENT",
    "FEATURE_SCREEN_DIMENSIONS_IN_QS",
    "FEATURE_BASE_DOMAIN_IN_QS",
    "FEATURE_AD_DIMENSIONS_IN_QS",
    "FEATURE_ASCENDANTS_AD_KEYWORD",
    "FEATURE_FIRST_PARENT_SIBLING_AD_ATTRIBUTE",
    "FEATURE_AD_DIMENSIONS_IN_COMPLETE_URL",
    #
    "FEATURE_VALID_QS",
    "FEATURE_FIRST_PARENT_ASYNC",
    "FEATURE_FIRST_PARENT_DEFER",
    "FEATURE_FIRST_PARENT_ATTR_ADDED_BY_SCRIPT",
    "FEATURE_FIRST_PARENT_ATTR_MODIFIED_BY_SCRIPT",
]

FEATURES_TO_PERTURBE_CAT = [
    "FEATURE_FIRST_PARENT_TAG_NAME",
    # "FEATURE_SECOND_PARENT_TAG_NAME",
    # "FEATURE_FIRST_PARENT_SIBLING_TAG_NAME"
]

FEATURES_TO_PERTURBE_BINARY_ALL = [
    "FEATURE_AD_KEYWORD_0",
    "FEATURE_AD_KEYWORD_1",
    "FEATURE_SPECIAL_CHAR_AD_KEYWORD_0",
    "FEATURE_SPECIAL_CHAR_AD_KEYWORD_1",
    "FEATURE_SEMICOLON_PRESENT_0",
    "FEATURE_SEMICOLON_PRESENT_1",
    "FEATURE_SCREEN_DIMENSIONS_IN_QS_0",
    "FEATURE_SCREEN_DIMENSIONS_IN_QS_1",
    "FEATURE_BASE_DOMAIN_IN_QS_0",
    "FEATURE_BASE_DOMAIN_IN_QS_1",
    "FEATURE_AD_DIMENSIONS_IN_QS_0",
    "FEATURE_AD_DIMENSIONS_IN_QS_1",
    "FEATURE_ASCENDANTS_AD_KEYWORD_0",
    "FEATURE_ASCENDANTS_AD_KEYWORD_1",
    "FEATURE_FIRST_PARENT_SIBLING_AD_ATTRIBUTE_0",
    "FEATURE_FIRST_PARENT_SIBLING_AD_ATTRIBUTE_1",
    "FEATURE_AD_DIMENSIONS_IN_COMPLETE_URL_0",
    "FEATURE_AD_DIMENSIONS_IN_COMPLETE_URL_1",
    #
    "FEATURE_VALID_QS_0",
    "FEATURE_VALID_QS_1",
    "FEATURE_FIRST_PARENT_ASYNC_0",
    "FEATURE_FIRST_PARENT_ASYNC_1",
    "FEATURE_FIRST_PARENT_DEFER_0",
    "FEATURE_FIRST_PARENT_DEFER_1",
    "FEATURE_FIRST_PARENT_ATTR_ADDED_BY_SCRIPT_0",
    "FEATURE_FIRST_PARENT_ATTR_ADDED_BY_SCRIPT_1",
    "FEATURE_FIRST_PARENT_ATTR_MODIFIED_BY_SCRIPT_0",
    "FEATURE_FIRST_PARENT_ATTR_MODIFIED_BY_SCRIPT_1",
]


FEATURES_TO_INCREASE_ONLY = [
    "FEATURE_GRAPH_NODES",
    "FEATURE_GRAPH_EDGES",
    # "FEATURE_URL_LENGTH",
    "FEATURE_INBOUND_OUTBOUND_CONNECTIONS",
    "FEATURE_FIRST_NUMBER_OF_SIBLINGS",
    "FEATURE_FIRST_PARENT_INBOUND_CONNECTIONS",
    "FEATURE_FIRST_PARENT_OUTBOUND_CONNECTIONS",
    "FEATURE_FIRST_PARENT_INBOUND_OUTBOUND_CONNECTIONS",
]

FEATURES_CATEGORICAL = [
    "FEATURE_NODE_CATEGORY",
    "FEATURE_FIRST_PARENT_TAG_NAME",
    "FEATURE_FIRST_PARENT_SIBLING_TAG_NAME",
    "FEATURE_SECOND_PARENT_TAG_NAME",
    "FEATURE_SECOND_PARENT_SIBLING_TAG_NAME"
]

FEATURES_TO_EXCLUDE_ADGRAPH = [
    "DOMAIN_NAME", 
    "NODE_ID",
    "FEATURE_KATZ_CENTRALITY", 
    "FEATURE_FIRST_PARENT_KATZ_CENTRALITY", 
    "FEATURE_SECOND_PARENT_KATZ_CENTRALITY"
]


# Binary
FEATURES_BINARY = [
    "FEATURE_DESCENDANTS",
    "FEATURE_SCRIPT_IS_ACTIVE",
    "FEATURE_SCRIPT_IS_EVAL_OR_FUNCTION",
    "FEATURE_DESCENDANTS_OF_SCRIPT",
    "FEATURE_ASCENDANTS_AD_KEYWORD",
    "FEATURE_DESCENDANT_OF_EVAL_OR_FUNCTION",
    "FEATURE_ASCENDANT_SCRIPT_HAS_EVAL_OR_FUNCTION",
    "FEATURE_ASCENDANT_SCRIPT_HAS_FINGERPRINTING_KEYWORD",
    "FEATURE_FIRST_PARENT_ASYNC",
    "FEATURE_FIRST_PARENT_DEFER",
    "FEATURE_FIRST_PARENT_SIBLING_AD_ATTRIBUTE",
    "FEATURE_FIRST_PARENT_NODE_ADDED_BY_SCRIPT",
    "FEATURE_FIRST_PARENT_NODE_REMOVED_BY_SCRIPT",
    "FEATURE_FIRST_PARENT_ATTR_ADDED_BY_SCRIPT",
    "FEATURE_FIRST_PARENT_ATTR_MODIFIED_BY_SCRIPT",
    "FEATURE_FIRST_PARENT_ATTR_REMOVED_BY_SCRIPT",
    "FEATURE_FIRST_PARENT_STYLE_ATTR_ADDED_BY_SCRIPT",
    "FEATURE_FIRST_PARENT_STYLE_ATTR_REMOVED_BY_SCRIPT",
    "FEATURE_SECOND_PARENT_ASYNC",
    "FEATURE_SECOND_PARENT_DEFER",
    "FEATURE_SECOND_PARENT_SIBLING_AD_ATTRIBUTE",
    "FEATURE_SECOND_PARENT_NODE_ADDED_BY_SCRIPT",
    "FEATURE_SECOND_PARENT_NODE_REMOVED_BY_SCRIPT",
    "FEATURE_SECOND_PARENT_ATTR_ADDED_BY_SCRIPT",
    "FEATURE_SECOND_PARENT_ATTR_MODIFIED_BY_SCRIPT",
    "FEATURE_SECOND_PARENT_ATTR_REMOVED_BY_SCRIPT",
    "FEATURE_SECOND_PARENT_STYLE_ATTR_ADDED_BY_SCRIPT",
    "FEATURE_SECOND_PARENT_STYLE_ATTR_REMOVED_BY_SCRIPT",
    "FEATURE_AD_KEYWORD",
    "FEATURE_VALID_QS",
    "FEATURE_SPECIAL_CHAR_AD_KEYWORD",
    "FEATURE_SEMICOLON_PRESENT",
    "FEATURE_BASE_DOMAIN_IN_QS",
    "FEATURE_AD_DIMENSIONS_IN_QS",
    "FEATURE_AD_DIMENSIONS_IN_COMPLETE_URL",
    "FEATURE_SCREEN_DIMENSIONS_IN_QS",
    "FEATURE_DOMAIN_PARTY",
    "FEATURE_SUB_DOMAIN_CHECK"
]

FEATURE_SCRIPT_IS_ACTIVE = [
    "FEATURE_SCRIPT_IS_ACTIVE_0",
    "FEATURE_SCRIPT_IS_ACTIVE_1"
]

FEATURE_SCRIPT_IS_EVAL_OR_FUNCTION = [
    "FEATURE_SCRIPT_IS_EVAL_OR_FUNCTION_0",
 "FEATURE_SCRIPT_IS_EVAL_OR_FUNCTION_1"
]

FEATURE_DESCENDANTS = [
    "FEATURE_DESCENDANTS_0",
    "FEATURE_DESCENDANTS_1"
]

FEATURE_DESCENDANTS_OF_SCRIPT = [
    "FEATURE_DESCENDANTS_OF_SCRIPT_0",
    "FEATURE_DESCENDANTS_OF_SCRIPT_1"
]

FEATURE_ASCENDANTS_AD_KEYWORD = [
    "FEATURE_ASCENDANTS_AD_KEYWORD_0",
    "FEATURE_ASCENDANTS_AD_KEYWORD_1"
]

FEATURE_DESCENDANT_OF_EVAL_OR_FUNCTION = [
    "FEATURE_DESCENDANT_OF_EVAL_OR_FUNCTION_0",
    "FEATURE_DESCENDANT_OF_EVAL_OR_FUNCTION_1"
]

FEATURE_ASCENDANT_SCRIPT_HAS_EVAL_OR_FUNCTION = [
    "FEATURE_ASCENDANT_SCRIPT_HAS_EVAL_OR_FUNCTION_0",
    "FEATURE_ASCENDANT_SCRIPT_HAS_EVAL_OR_FUNCTION_1"
]

FEATURE_ASCENDANT_SCRIPT_HAS_FINGERPRINTING_KEYWORD = [
    "FEATURE_ASCENDANT_SCRIPT_HAS_FINGERPRINTING_KEYWORD_0",
    "FEATURE_ASCENDANT_SCRIPT_HAS_FINGERPRINTING_KEYWORD_1"
]

FEATURE_FIRST_PARENT_ASYNC = [
    "FEATURE_FIRST_PARENT_ASYNC_0",
    "FEATURE_FIRST_PARENT_ASYNC_1"
]

FEATURE_FIRST_PARENT_DEFER = [
    "FEATURE_FIRST_PARENT_DEFER_0",
    "FEATURE_FIRST_PARENT_DEFER_1"
]

FEATURE_FIRST_PARENT_SIBLING_AD_ATTRIBUTE = [
    "FEATURE_FIRST_PARENT_SIBLING_AD_ATTRIBUTE_0",
    "FEATURE_FIRST_PARENT_SIBLING_AD_ATTRIBUTE_1"
]

FEATURE_FIRST_PARENT_NODE_ADDED_BY_SCRIPT = [
    "FEATURE_FIRST_PARENT_NODE_ADDED_BY_SCRIPT_0"
 "FEATURE_FIRST_PARENT_NODE_ADDED_BY_SCRIPT_1"
]
 
FEATURE_FIRST_PARENT_NODE_REMOVED_BY_SCRIPT = [
    "FEATURE_FIRST_PARENT_NODE_REMOVED_BY_SCRIPT_0"
 "FEATURE_FIRST_PARENT_NODE_REMOVED_BY_SCRIPT_1"
]
 
FEATURE_FIRST_PARENT_ATTR_ADDED_BY_SCRIPT = [
    "FEATURE_FIRST_PARENT_ATTR_ADDED_BY_SCRIPT_0"
 "FEATURE_FIRST_PARENT_ATTR_ADDED_BY_SCRIPT_1"
]

FEATURE_FIRST_PARENT_ATTR_MODIFIED_BY_SCRIPT = [
    "FEATURE_FIRST_PARENT_ATTR_MODIFIED_BY_SCRIPT_0"
 "FEATURE_FIRST_PARENT_ATTR_MODIFIED_BY_SCRIPT_1"
]

FEATURE_FIRST_PARENT_ATTR_REMOVED_BY_SCRIPT = [
    "FEATURE_FIRST_PARENT_ATTR_REMOVED_BY_SCRIPT_0",
 "FEATURE_FIRST_PARENT_ATTR_REMOVED_BY_SCRIPT_1"
]

FEATURE_FIRST_PARENT_STYLE_ATTR_ADDED_BY_SCRIPT = [
    "FEATURE_FIRST_PARENT_STYLE_ATTR_ADDED_BY_SCRIPT_0"
 "FEATURE_FIRST_PARENT_STYLE_ATTR_ADDED_BY_SCRIPT_1"
]

FEATURE_FIRST_PARENT_STYLE_ATTR_REMOVED_BY_SCRIPT = [
    "FEATURE_FIRST_PARENT_STYLE_ATTR_REMOVED_BY_SCRIPT_0"
 "FEATURE_FIRST_PARENT_STYLE_ATTR_REMOVED_BY_SCRIPT_1"
]

FEATURE_SECOND_PARENT_ASYNC = [
    "FEATURE_SECOND_PARENT_ASYNC_0",
    "FEATURE_SECOND_PARENT_ASYNC_1"
]

FEATURE_SECOND_PARENT_DEFER = [
    "FEATURE_SECOND_PARENT_DEFER_0",
    "FEATURE_SECOND_PARENT_DEFER_1"
]

FEATURE_SECOND_PARENT_SIBLING_AD_ATTRIBUTE = [
    "FEATURE_SECOND_PARENT_SIBLING_AD_ATTRIBUTE_0",
 "FEATURE_SECOND_PARENT_SIBLING_AD_ATTRIBUTE_1"
]

FEATURE_SECOND_PARENT_NODE_ADDED_BY_SCRIPT = [
    "FEATURE_SECOND_PARENT_NODE_ADDED_BY_SCRIPT_0",
 "FEATURE_SECOND_PARENT_NODE_ADDED_BY_SCRIPT_1"
]

FEATURE_SECOND_PARENT_NODE_REMOVED_BY_SCRIPT = [
    "FEATURE_SECOND_PARENT_NODE_REMOVED_BY_SCRIPT_0",
 "FEATURE_SECOND_PARENT_NODE_REMOVED_BY_SCRIPT_1"
]

FEATURE_SECOND_PARENT_ATTR_ADDED_BY_SCRIPT = [
    "FEATURE_SECOND_PARENT_ATTR_ADDED_BY_SCRIPT_0",
 "FEATURE_SECOND_PARENT_ATTR_ADDED_BY_SCRIPT_1"
]

FEATURE_SECOND_PARENT_ATTR_MODIFIED_BY_SCRIPT = [
    "FEATURE_SECOND_PARENT_ATTR_MODIFIED_BY_SCRIPT_0",
 "FEATURE_SECOND_PARENT_ATTR_MODIFIED_BY_SCRIPT_1"
]

FEATURE_SECOND_PARENT_ATTR_REMOVED_BY_SCRIPT = [
    "FEATURE_SECOND_PARENT_ATTR_REMOVED_BY_SCRIPT_0",
 "FEATURE_SECOND_PARENT_ATTR_REMOVED_BY_SCRIPT_1"
]

FEATURE_SECOND_PARENT_STYLE_ATTR_ADDED_BY_SCRIPT = [
    "FEATURE_SECOND_PARENT_STYLE_ATTR_ADDED_BY_SCRIPT_0",
 "FEATURE_SECOND_PARENT_STYLE_ATTR_ADDED_BY_SCRIPT_1"
]

FEATURE_SECOND_PARENT_STYLE_ATTR_REMOVED_BY_SCRIPT = [
    "FEATURE_SECOND_PARENT_STYLE_ATTR_REMOVED_BY_SCRIPT_0",
 "FEATURE_SECOND_PARENT_STYLE_ATTR_REMOVED_BY_SCRIPT_1"
]

FEATURE_AD_KEYWORD = [
    "FEATURE_AD_KEYWORD_0",
    "FEATURE_AD_KEYWORD_1"
]

FEATURE_SPECIAL_CHAR_AD_KEYWORD = [
    "FEATURE_SPECIAL_CHAR_AD_KEYWORD_0",
    "FEATURE_SPECIAL_CHAR_AD_KEYWORD_1"
]

FEATURE_SEMICOLON_PRESENT = [
    "FEATURE_SEMICOLON_PRESENT_0",
    "FEATURE_SEMICOLON_PRESENT_1"
]

FEATURE_BASE_DOMAIN_IN_QS = [
    "FEATURE_BASE_DOMAIN_IN_QS_0",
    "FEATURE_BASE_DOMAIN_IN_QS_1"
]

FEATURE_AD_DIMENSIONS_IN_QS = [
    "FEATURE_AD_DIMENSIONS_IN_QS_0",
    "FEATURE_AD_DIMENSIONS_IN_QS_1"
]

FEATURE_AD_DIMENSIONS_IN_COMPLETE_URL = [
    "FEATURE_AD_DIMENSIONS_IN_COMPLETE_URL_0",
    "FEATURE_AD_DIMENSIONS_IN_COMPLETE_URL_1"
]

FEATURE_SCREEN_DIMENSIONS_IN_QS = [
    "FEATURE_SCREEN_DIMENSIONS_IN_QS_0",
    "FEATURE_SCREEN_DIMENSIONS_IN_QS_1"
]

FEATURE_DOMAIN_PARTY = [
    "FEATURE_DOMAIN_PARTY_0",
    "FEATURE_DOMAIN_PARTY_1"
]

FEATURE_SUB_DOMAIN_CHECK = [
    "FEATURE_SUB_DOMAIN_CHECK_0",
    "FEATURE_SUB_DOMAIN_CHECK_1"
]

FEATURE_VALID_QS = [
    "FEATURE_VALID_QS_0",
    "FEATURE_VALID_QS_1"
]
