FEATURES_TO_PERTURBE = [
    "FEATURE_URL_LENGTH",
    "FEATURE_SEMICOLON_IN_QUERY",

    "FEATURE_IN_DEGREE",
    "FEATURE_OUT_DEGREE",
    "FEATURE_IN_OUT_DEGREE",

    "FEATURE_PARENT_IN_DEGREE",
    "FEATURE_PARENT_OUT_DEGREE",
    "FEATURE_PARENT_IN_OUT_DEGREE",

    "FEATURE_AVERAGE_DEGREE_CONNECTIVITY",
    
    "FEATURE_MODIFIED_BY_SCRIPT",
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT"
]

FEATURES_TO_PERTURBE_NUMERIC = [
    "FEATURE_URL_LENGTH",

    "FEATURE_IN_DEGREE",
    "FEATURE_OUT_DEGREE",
    "FEATURE_IN_OUT_DEGREE",

    "FEATURE_PARENT_IN_DEGREE",
    "FEATURE_PARENT_OUT_DEGREE",
    "FEATURE_PARENT_IN_OUT_DEGREE",

    "FEATURE_AVERAGE_DEGREE_CONNECTIVITY",
]

FEATURES_TO_PERTURBE_BINARY = [
    "FEATURE_SEMICOLON_IN_QUERY",
    "FEATURE_MODIFIED_BY_SCRIPT",
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT",
]

FEATURES_TO_PERTURBE_CAT = [
]

FEATURES_TO_PERTURBE_BINARY_ALL = [
    "FEATURE_SEMICOLON_IN_QUERY_0",
    "FEATURE_SEMICOLON_IN_QUERY_1",
    "FEATURE_MODIFIED_BY_SCRIPT_0",
    "FEATURE_MODIFIED_BY_SCRIPT_1",
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT_0",
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT_1"
]

FEATURES_TO_PERTURBE_CAT_ALL = [
]

FEATURES_TO_INCREASE_ONLY = [
    # "FEATURE_URL_LENGTH",
    "FEATURE_IN_DEGREE",
    "FEATURE_OUT_DEGREE",
    "FEATURE_IN_OUT_DEGREE",

    "FEATURE_PARENT_IN_DEGREE",
    "FEATURE_PARENT_OUT_DEGREE",
    "FEATURE_PARENT_IN_OUT_DEGREE",
]

FEATURES_CATEGORICAL = [
    "FEATURE_RESOURCE_TYPE",
]

FEATURES_TO_EXCLUDE_PAGEGRAPH = [
    "NETWORK_REQUEST_URL", 
    "FINAL_URL",
    # "top_level_url"
]


# Categorical, Binary features lists

# Binary
FEATURES_BINARY = [
    "FEATURE_FROM_SUBDOMAIN",
    "FEATURE_FROM_THIRD_PARTY",
    "FEATURE_SEMICOLON_IN_QUERY",
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT",
    "FEATURE_MODIFIED_BY_SCRIPT",
]

FEATURE_FROM_SUBDOMAIN = [
    "FEATURE_FROM_SUBDOMAIN_0",
    "FEATURE_FROM_SUBDOMAIN_1"
]

FEATURE_FROM_THIRD_PARTY = [
    "FEATURE_FROM_THIRD_PARTY_0",
    "FEATURE_FROM_THIRD_PARTY_1"
]

FEATURE_SEMICOLON_IN_QUERY = [
    "FEATURE_SEMICOLON_IN_QUERY_0",
    "FEATURE_SEMICOLON_IN_QUERY_1"
]

FEATURE_PARENT_MODIFIED_BY_SCRIPT = [
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT_0",
    "FEATURE_PARENT_MODIFIED_BY_SCRIPT_1"
]

FEATURE_MODIFIED_BY_SCRIPT = [
    "FEATURE_MODIFIED_BY_SCRIPT_0",
    "FEATURE_MODIFIED_BY_SCRIPT_1"
]

